### ISSUE TITLE
Is kroto-plus compatible with Kotlin Native (multiplatform)?

### ISSUE THREAD

**Issue by bourquep** [marcoferrer/kroto-plus#110]
I am evaluating Kotlin Multiplatform for an upcoming project which consist of Android, iOS and Web frontend apps that need to interact with a gRpc API.

Would the code generated by kroto-plus work on all those platforms? As far as I can tell from the docs, since the gRpc stuff is based on gRpc-java, it would probably not work on the non-JVM platforms supported by KMP. But maybe I am mistaken?

If indeed gRpc is not multiplatform, would the Kotlin classes generated from my protobuf messages work on all platforms, including encoding/decoding those messages?

**Comment by marcoferrer** [comment]
Sorry about the time it's taken me to respond to this. I was recently under the weather.

Unfortunately, this project solely targets Kotlin on the JVM due to its dependency on `grpc-java`. There is work to at least support protobuf models using multiplatform kotlinx serialization but its still in poc stages.
