### ISSUE TITLE
pb-and-k support

### ISSUE THREAD

**Issue by Globegitter** [marcoferrer/kroto-plus#89]
It would be nice to be able to fully utilise kotlin features, also for the protobuf creation itself. What do you think of supporting https://github.com/cretz/pb-and-k - would this be something feasible/useful?

**Comment by marcoferrer** [comment]
I have no opposition to supporting pb-and-k. I was actually very interested in it. Originally I was working on a poc to support it but the author mentioned [here](https://github.com/marcoferrer/kroto-plus/issues/21#issuecomment-485494484) that he didnt have capacity anymore to support pb-and-k. 

The other full kotlin protobuf alternative is kotlinx serialization. I had placed a hold on integration with that project since it was still lacking support for some proto3 features like `oneof` at the time.

**Comment by Globegitter** [comment]
Thanks for the quick response, there is also wire, but it also has only limited proto3 support. Is the issue you are referring to: https://github.com/Kotlin/kotlinx.serialization/issues/67?

But either way the reasoning makes total sense for not supporting pb-and-k, so the issue can be closed.

**Comment by Globegitter** [comment]
@marcoferrer Turns out an organisation has forked pb-and-k and is now maintaining it: https://github.com/streem/pbandk could be worth taking a look at.

**Comment by RdeWilde** [comment]
Also kotlinx serialization has progressed. We should be good to go. Where to start?
